#!/bin/bash

#   CMCompiler is free software. It comes without any warranty, to
#   the extent permitted by applicable law. You can redistribute it
#   and/or modify it under the terms of the Do What The Fuck You Want
#   To Public License, Version 2, as published by Sam Hocevar. See
#   http://sam.zoy.org/wtfpl/COPYING for more details.

call=$1
DIR="/usr/share/cmcompiler/prog"

if [ "$call" == "--compile" ]; then
	python $DIR/build.py
elif [ "$call" == "--sync" ]; then
	python $DIR/sync.py
elif [ "$call" == "--download" ]; then
	python $DIR/dl_dialog.py
else
	python $DIR/cmcompiler.py
fi
